version: '3'
services: 
    # https://ci.apache.org/projects/flink/flink-docs-master/docs/deployment/resource-providers/standalone/docker/
    jobmanager:
        image: flink:scala_2.12-java11
        ports: 
            - 8081:8081
        environment: 
            FLINK_PROPERTIES: "jobmanager.rpc.address: jobmanager"
        command: jobmanager
    taskmanager:
        image: flink:scala_2.12-java11
        environment: 
            FLINK_PROPERTIES: "jobmanager.rpc.address: jobmanager"
        command: taskmanager

    kafka:
        image: confluentinc/cp-kafka:5.4.4
        environment:
            KAFKA_ZOOKEEPER_CONNECT: zookeeper:32181
            KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
            KAFKA_BROKER_ID: 2
            KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

    zookeeper:
        image: confluentinc/cp-zookeeper:5.4.4
        environment:
            ZOOKEEPER_CLIENT_PORT: 32181

    schema-registry:
        image: confluentinc/cp-schema-registry:5.4.4